server:
  port: 8080

# mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: AUTO
      field-strategy: NOT_EMPTY
      db-type: h2
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#spring
spring:
  # H2 DATABASE
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: root
    initialization-mode: always
    continue-on-error: true
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-mysql.sql
    data: classpath:db/data-mysql.sql
  jackson:
    default-property-inclusion: non_null

# logging
logging:
  level.root: info
  level.com.forest: debug